# RoleBinding for Spark ServiceAccount in dfp namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: dfp
  labels:
    app.kubernetes.io/name: spark
    app.kubernetes.io/component: spark-applications
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: dfp
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding for Spark ServiceAccount in kubeflow namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: spark
    app.kubernetes.io/component: spark-applications
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: kubeflow
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
